import puppeteer from 'puppeteer';
const b = await puppeteer.launch({ args: ['--no-sandbox','--ignore-certificate-errors'] });
const p = await b.newPage();
await p.setViewport({ width: 390, height: 780, isMobile: true, hasTouch: true });
const errs = [];
p.on('console', m => m.type()==='error' && errs.push(m.text()));
p.on('pageerror', e => errs.push(e.message));
await p.goto('https://shardfall.night.enkiduck.com/', { waitUntil: 'networkidle0' });
await new Promise(r=>setTimeout(r,500));
await p.click('#ovBtn');
await new Promise(r=>setTimeout(r,300));
await p.click('#dialog').catch(()=>{});
await new Promise(r=>setTimeout(r,400));
const s = await p.evaluate(()=>({state:window.__g?.state, floor:window.__g?.floorNum, enemies:window.__g?.enemies.length}));
await p.screenshot({path:'live.png'});
await b.close();
console.log('live state:', JSON.stringify(s));
console.log('errors:', errs.length?errs:'NONE');
process.exit(errs.length?1:0);
